import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { getCookie } from "./actions/cookies/getCookie.action";
import { COOKIES_KEYS } from "@/lib/staticKeys";
import initTranslations from "../../i18n";
import TranslationsProvider from "@/components/providers/TranslationsProvider";

const quicksand = localFont({
  src: "../../public/fonts/Quicksand-VariableFont_wght.ttf",
  variable: "--font-quicksand",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const locale = await getCookie(COOKIES_KEYS.locale);
  const { resources, i18n } = await initTranslations(locale, ["locale"]);

  return (
    <html lang={locale} dir={i18n.dir()}>
      <body className={`${quicksand.variable} antialiased`}>
        <TranslationsProvider
          resources={resources}
          locale={locale}
          namespaces={["locale"]}
        >
          {children}
        </TranslationsProvider>
      </body>
    </html>
  );
}
